logging-util/main/default/objects/QDX_Log__c/QDX_Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

logging-util/main/default/objects/QDX_LogSetting__c/QDX_LogSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for QDX logging level</description>
    <label>QDX Log Setting</label>
</CustomObject>

logging-util-2/main/default/objects/QDX_LogSetting__c/fields/Days_To_Expire__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Expire__c</fullName>
    <defaultValue>30</defaultValue>
    <inlineHelpText>How long the Log records will be kept in system. Only the org level setting is considered for this.</inlineHelpText>
    <label>Days To Expire</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

logging-util-2/main/default/classes/QDX_LogArchiveBatch.cls
/*
* @author Qamar Islam (https://github.com/qislam)
*/
global with sharing class QDX_LogArchiveBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        QDX_LogSetting__c settings = QDX_LogSetting__c.getOrgDefaults();
        Integer cutoffDays = (Integer)settings.Days_to_Expire__c;
        Datetime cutoffDate = System.today().addDays(0 - cutoffDays);
        String query = 'SELECT Id FROM QDX_Log__c WHERE CreatedDate < :cutoffDate';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<sObject> scope) {
        delete scope;
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Log Archive Batch Finished');
    }
}