base-utils/main/default/objects/QDX_Property__mdt/QDX_Property__mdt.object-meta.xml
<CustomObject>
    <label>QDX Property</label>
    <pluralLabel>QDX Properties</pluralLabel>
</CustomObject>

base-utils/main/default/objects/QDX_Property__mdt/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

base-utils/main/default/objects/QDX_Property__mdt/fields/QDX_SF_Instance__c.field-meta.xml
<CustomField>
    <fullName>QDX_SF_Instance__c</fullName>
    <description>Name of sandbox to which current setting is applicable.</description>
    <label>QDX SF Instance</label>
    <referenceTo>QDX_SF_Instance__mdt</referenceTo>
    <relationshipLabel>QDX Properties</relationshipLabel>
    <relationshipName>QDX_Properties</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_SF_Instance__mdt/QDX_SF_Instance__mdt.object-meta.xml
<CustomObject>
    <description>To track the name of sandboxes.</description>
    <label>QDX SF Instance</label>
    <pluralLabel>QDX SF Instances</pluralLabel>
</CustomObject>

base-utils/main/default/classes/QDX_Property.cls
public with sharing class QDX_Property {
    public String value {
        get {
            if (this.value == null) {
                if (this.selectedProperty == null) {
                    this.value = '';
                } else {
                    this.value = this.selectedProperty.Value__c;
                }
            }
            return this.value;
        }
        private set;
    }

    public static QDX_Property forLabel(String propertyLabel) {
        return new QDX_Property(propertyLabel);
    }

    private QDX_Property__mdt selectedProperty;

    private QDX_Property(String propertyLabel) {
        System.Domain domainObj = DomainParser.parse(URL.getSalesforceBaseUrl().toExternalForm());
        String sandboxName = domainObj.getSandboxName();
        String instanceName = sandboxName == null ? 'PRODUCTION' : sandboxName.toUpperCase();

        QDX_Property__mdt[] properties = [
            SELECT DeveloperName
            , Label
            , Value__c
            , isDefault__c
            , QDX_SF_Instance__c
            , QDX_SF_Instance__r.DeveloperName
            FROM QDX_Property__mdt
            WHERE Label = :propertyLabel
        ];

        for (QDX_Property__mdt current : properties) {
            if (current.QDX_SF_Instance__r.DeveloperName == instanceName) {
                selectedProperty = current;
                break;
            }
            if (current.isDefault__c) {
                selectedProperty = current;
            }
        }
    }
}