base-utils/main/default/objects/QDX_Property__mdt/QDX_Property__mdt.object-meta.xml
<CustomObject>
    <label>QDX Property</label>
    <pluralLabel>QDX Properties</pluralLabel>
</CustomObject>

base-utils/main/default/objects/QDX_Property__mdt/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/LongTextValue__c.field-meta.xml
<CustomField>
    <fullName>LongTextValue__c</fullName>
    <label>Value (Long Text)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/NumberValue__c.field-meta.xml
<CustomField>
    <fullName>NumberValue__c</fullName>
    <label>Value (Number)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/ProfileId__c.field-meta.xml
<CustomField>
    <fullName>ProfileId__c</fullName>
    <inlineHelpText>Requires SF Instance to be set as well. If Sf Instance not set, this will be ignored.</inlineHelpText>
    <label>ProfileId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/QDX_SF_Instance__c.field-meta.xml
<CustomField>
    <fullName>QDX_SF_Instance__c</fullName>
    <description>Name of sandbox to which current setting is applicable.</description>
    <label>SF Instance</label>
    <referenceTo>QDX_SF_Instance__mdt</referenceTo>
    <relationshipLabel>QDX Properties</relationshipLabel>
    <relationshipName>QDX_Properties</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <inlineHelpText>Requires SF Instance to be set as well. If Sf Instance not set, this will be ignored.</inlineHelpText>
    <label>UserName</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_SF_Instance__mdt/QDX_SF_Instance__mdt.object-meta.xml
<CustomObject>
    <description>To track the name of sandboxes.</description>
    <label>QDX SF Instance</label>
    <pluralLabel>QDX SF Instances</pluralLabel>
</CustomObject>

property-toggle-util/main/default/classes/QDX_Property.cls
/*
* @author Qamar Islam (https://github.com/qislam)
* @description This class is for standard property.
*/
public with sharing class QDX_Property {
    public String value {
        get {
            if (this.value == null) {
                this.value = this.textValue;
            }
            return this.value;
        }
        private set;
    }

    public String textValue {
        get {
            if (this.textValue == null) {
                this.textValue = this.selectedProperty?.TextValue__c;
                if (String.isNotBlank(this.selectedProperty?.LongTextValue__c)) {
                    this.textValue = this.selectedProperty?.LongTextValue__c;
                }
                if (this.textValue == null) { this.textValue = ''; }
            }
            return this.textValue;
        }
        private set;
    }

    public Decimal numberValue {
        get {
            if (this.numberValue == null) {
                this.numberValue = this.selectedProperty?.NumberValue__c;
                if (this.numberValue == null) {
                    this.numberValue = 0;
                }
            }
            return this.numberValue;
        }
        private set;
    }

    public Boolean isActive {
        get {
            if (this.isActive == null) {
                this.isActive = this.selectedProperty?.isActive__c;
                if (this.isActive == null) { this.isActive = false; }
            }
            return this.isActive;
        }
        private set;
    }

    public Boolean isFound {
        get {
            if (this.isFound == null) {
                this.isFound = false;
                if (this.selectedProperty != null) { this.isFound = true; }
            }
            return this.isFound;
        }
        private set;
    }

    public static QDX_Property forLabel(String propertyLabel) {
        return new QDX_Property(propertyLabel);
    }

    private QDX_Property__mdt selectedProperty;
    @TestVisible private static QDX_Property__mdt testProperty;

    private QDX_Property(String propertyLabel) {
        System.Domain domainObj = DomainParser.parse(URL.getSalesforceBaseUrl().toExternalForm());
        String sandboxName = domainObj.getSandboxName();
        String instanceName = sandboxName == null ? 'PRODUCTION' : sandboxName.toUpperCase();

        QDX_Property__mdt[] properties = [
            SELECT DeveloperName
            , Label
            , TextValue__c
            , LongTextValue__c
            , NumberValue__c
            , isActive__c
            , isDefault__c
            , ProfileId__c
            , UserName__c
            , QDX_SF_Instance__c
            , QDX_SF_Instance__r.DeveloperName
            FROM QDX_Property__mdt
            WHERE Label = :propertyLabel
            ORDER BY UserName__c NULLS LAST
            , ProfileId__c NULLS LAST
            , QDX_SF_Instance__c NULLS LAST
        ];

        if (Test.isRunningTest() && testProperty != null) {
            properties.add(testProperty);
        }

        for (QDX_Property__mdt current : properties) {
            if (current.UserName__c == UserInfo.getUserName() && current.QDX_SF_Instance__r.DeveloperName == instanceName) { selectedProperty = current; break; }
            
            if (current.ProfileId__c == UserInfo.getProfileId() && current.QDX_SF_Instance__r.DeveloperName == instanceName) { selectedProperty = current; break; }
            
            if (String.isBlank(current.UserName__c) && String.isBlank(current.ProfileId__c) && current.QDX_SF_Instance__r.DeveloperName == instanceName) { selectedProperty = current; break; }
            
            if (current.isDefault__c) {
                selectedProperty = current;
            }
        }
    }
}