base-utils/main/default/objects/QDX_Property__mdt/QDX_Property__mdt.object-meta.xml
<CustomObject>
    <label>QDX Property</label>
    <pluralLabel>QDX Properties</pluralLabel>
</CustomObject>

base-utils/main/default/objects/QDX_Property__mdt/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

property-toggle-util/main/default/objects/QDX_Property__mdt/fields/LongTextValue__c.field-meta.xml
<CustomField>
    <fullName>LongTextValue__c</fullName>
    <label>Value (Long Text)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

property-toggle-util/main/default/classes/QDX_PropertyTest.cls
@isTest
public with sharing class QDX_PropertyTest {
    @isTest static void itShouldReturnPropertyValue() {
        QDX_Property__mdt testProperty = new QDX_Property__mdt();
        testProperty.Label = 'TestProperty';
        testProperty.DeveloperName = 'TestProperty';
        testProperty.LongTextValue__c = 'Test value';
        testProperty.isDefault__c = true;

        QDX_Property.testProperty = testProperty;

        String myValue = QDX_Property.forLabel('TestProperty').value;
        Boolean isActive = QDX_Property.forLabel('TestProperty').isActive;
        Decimal myNumber = QDX_Property.forLabel('TestProperty').numberValue;

        System.assert(myValue == 'Test Value', 'No value found');
        System.assert(isActive == false, 'No boolean found');
        System.assert(myNumber == 0, 'No number found');
    }
}